Knjiznica-projekt/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KnjiznicaProjekt.Models;

namespace KnjiznicaProjekt.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Knjiznica-projekt/Controllers/KnjigaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KnjiznicaProjekt.Data;
using KnjiznicaProjekt.Models;
using Microsoft.AspNetCore.Authorization;

namespace KnjiznicaProjekt.Controllers
{
    public class KnjigaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public KnjigaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Knjiga

        public async Task<IActionResult> Index(string trazi)
        {
            /*
            var applicationDbContext = _context.Knjiga.Include(k => k.Autor);
            return View(await applicationDbContext.ToListAsync());
            */
            var knjige = from k in _context.Knjiga
                          select k; //LINQ izvlačimo knjige na searchu
            if (!String.IsNullOrEmpty(trazi))//provjera jeli trazi postavljen
            {
                knjige = knjige.Where(s => s.Naziv.Contains(trazi));
            }
            var autor = from a in _context.Autor
                        select a;
            foreach (var item in knjige)
            {
                foreach(var item2 in autor)
                {
                    if (item.AutorId == item2.Id) item.Autor = item2;   
                }
            }
            return View(knjige.ToList());
        }

        // GET: Knjiga/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knjiga = await _context.Knjiga
                .Include(k => k.Autor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (knjiga == null)
            {
                return NotFound();
            }

            return View(knjiga);
        }

        // GET: Knjiga/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["AutorId"] = new SelectList(_context.Set<Autor>(), "Id", "Id");
            return View();
        }

        // POST: Knjiga/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Godina,AutorId")] Knjiga knjiga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(knjiga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutorId"] = new SelectList(_context.Set<Autor>(), "Id", "Id", knjiga.AutorId);
            return View(knjiga);
        }

        // GET: Knjiga/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knjiga = await _context.Knjiga.SingleOrDefaultAsync(m => m.Id == id);
            if (knjiga == null)
            {
                return NotFound();
            }
            ViewData["AutorId"] = new SelectList(_context.Set<Autor>(), "Id", "Id", knjiga.AutorId);
            return View(knjiga);
        }

        // POST: Knjiga/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,Godina,AutorId")] Knjiga knjiga)
        {
            if (id != knjiga.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(knjiga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KnjigaExists(knjiga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutorId"] = new SelectList(_context.Set<Autor>(), "Id", "Id", knjiga.AutorId);
           // ViewData["Autor"] = new SelectList(_context.Set<Autor>(), "Autor", "Autor", knjiga.Autor);
            return View(knjiga);
        }

        // GET: Knjiga/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knjiga = await _context.Knjiga
                .Include(k => k.Autor)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (knjiga == null)
            {
                return NotFound();
            }

            return View(knjiga);
        }

        // POST: Knjiga/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var knjiga = await _context.Knjiga.SingleOrDefaultAsync(m => m.Id == id);
            _context.Knjiga.Remove(knjiga);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KnjigaExists(int id)
        {
            return _context.Knjiga.Any(e => e.Id == id);
        }
    }
}

Knjiznica-projekt/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Knjiznica-projekt/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Kontakt";
}
<h2>@ViewData["Title"]</h2>

<address>
    <strong>podrška:</strong> <a href="mailto:tkuhar6443@gmail.com">tkuhar6443@gmail.com</a><br />
</address>

<address>
    Žminjska 7<br />
    Zagreb, 10000<br />
    <abbr title="Phone">P: </abbr>
    +385998403841
</address>

<!-- Add Google Maps -->
<div id="googleMap" style="height:400px;width:100%;"></div>
<script>
        function myMap() {
            var myCenter = new google.maps.LatLng(45.808814, 16.038976);
            var mapProp = {center:myCenter, zoom:5, scrollwheel:false, draggable:true, gestureHandling: 'greedy', mapTypeId:google.maps.MapTypeId.ROADMAP};
            var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
            var marker = new google.maps.Marker({position:myCenter});
            marker.setMap(map);
        }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcXjOMrPxBJD2aUF_8Xi92B6jQ-2dV95A&callback=myMap"></script>

Knjiznica-projekt/Views/Home/Index.cshtml
@model IEnumerable<KnjiznicaProjekt.Models.Knjiga>
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <a asp-controller="Knjiga" asp-action="Index"> <img src="~/images/img_4_res.jpg" alt=" " class="img-responsive" /></a>
        </div>
        <div class="item">
            <a asp-controller="Knjiga" asp-action="Index"> <img src="~/images/img_1_res.jpg" alt=" " class="img-responsive" /></a>
        </div>
        <div class="item">
            <a asp-controller="Knjiga" asp-action="Index"> <img src="~/images/img_2_res.jpg" alt=" " class="img-responsive" /></a>
        </div>
        <div class="item">
            <a asp-controller="Knjiga" asp-action="Index"> <img src="~/images/img_3_res.jpg" alt=" " class="img-responsive" /></a>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!--
<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>
-->
<div style="padding: 60px 50px;">
    <div class="row">
        <div class="col-sm-8" style="margin-top:50px;">
            <h2>Zanimljivosti iz svijeta knjige</h2><br>
                                                    <h4>
                                                        Najmanja knjiga na svijetu tiskana je u Japanu i zove se Sezonsko cvijeće. S promjerom hrpta od samo 0,7 milimetara njezin sadržaj nevidljiv je golom oku, stoga je treba čitati povećalom.<br /><br />
                                                        Najveća knjiga na svijetu nazvana Najbolje svjetske misli duga je 3,20 i široka 2 metra, a njezinih 160 stranica teži 250 kilograma.<br /><br />
                                                        Od najčitanijih knjiga u posljednjih pedeset godina, na prvom mjestu i dalje je uvjerljivo Biblija.<br /><br />
                                                    </h4>
        </div>
        <div class="col-sm-4">
            <span class="glyphicon glyphicon-education logo" style="font-size:100px;"></span>
        </div>
    </div>
</div>

<div style="background-color: #f6f6f6;padding:60px 50px">
    <div class="row">
        <div class="col-sm-4">
            <span class="glyphicon glyphicon-info-sign logo slideanim" style="font-size:100px;"></span>
        </div>
        <div class="col-sm-8">
            <h2>Zašto čitati?</h2><br>
            <h4><strong>Čitanje ublažava stres za čak 60 posto</strong></h4><br>
            <p><strong>Za opuštene mišiće i slabije otkucaje srca dovoljno je samo šest minuta čitanja bez stanke. Osim smanjenog stresa, čitanje nam obogaćuje iskustvo i vokabular zbog čega smo samouvjereniji<br /><br />Čitanjem knjiga izlažete većim količinama informacija, pa ćete moći osmisliti kreativnije ideje. Čitate li mnogo knjiga o području posla kojim se bavite, počet ćete kombinirati znanje iz njih i osmišljavati rješenja koja nisu nigdje zapisana.</strong></p>
        </div>
    </div>
</div>